<?php


namespace App\Lib;

use \Illuminate\Support\Facades\Facade;

class TransliterationService extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'transliterationString'; // TODO: Change the autogenerated stub
    }
}
